[build]
  publish = "staticfiles"  # This is where the static files are collected
  command = "python manage.py collectstatic --noinput"

[build.environment]
  DJANGO_SETTINGS_MODULE = "templates.udemyclone.settings"  # Replace with your project settings module
  PYTHON_VERSION = "3.11"  # Specify your Python version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
